### PR TITLE
Correct the value of `reset_time` for MovingWindow strategy

### PR DESCRIPTION
**Pull request by alisaifee**
# Description
The value of `reset_time` for the moving window strategy is currently derived from the newest entry in the moving window instead of the oldest.

# Related issues
- #200

### CODE REVIEW

**Comment by alisaifee** [comment]
@skalpel: if you could try this branch out with any other usecases you have I'd appreciate that!

**Comment by skalpel** [comment]
For my use case (sync rate limiting with in-memory storage) it works excellent!

**Comment by skalpel** [comment]
@alisaifee just out of curiosity, when is it going to be released?

**Comment by alisaifee** [comment]
> @alisaifee just out of curiosity, when is it going to be released?

Sorry about the delay - now available in `3.10.0`

**Comment by skalpel** [comment]
Thanks a lot!

**Pull request merged**
