### PR TITLE
Increased default timeout for mongodb to 10 seconds to accomodate slow connections, considering production replica sets and sharding.

### PR DESCRIPTION
**Pull request by Vishwamithra37**
## Summary by CodeRabbit

- **Refactor**
	- Improved database connection stability by increasing timeout settings.

### CODE REVIEW

**Comment by alisaifee** [comment]
@Vishwamithra37 that default value is too high - if in your setup that is expected why not pass it in explicitly?

**Comment by Vishwamithra37** [comment]
> @Vishwamithra37 that default value is too high - if in your setup that is expected why not pass it in explicitly?

I believe 10s is okay. Because of the following reasons:

1. In my and many setups I know where flask-limiter is used, (a wrapper which uses limits library), it is not obvious as to where and how to pass on the connection options for the Database. 
2. **Given it is not obvious and the dev need to seperately mention the timeout for the limits library again -- Assuming they also mention the same in their normal database operations config, 10s is actually too low, the 10s is just enough for developing upon replica sets and sharded databases locally.**
3. The 1s is far too low and will only work when there is a single instance of the DB working. (In my specific case mongodb).  And since this library is used as secondary, it can get hard to find out why exactly the error is occuring.  In the case of replica set:
[ServerSelectionTimeoutError on mongo replica set using pymongo](https://stackoverflow.com/questions/71132796/serverselectiontimeouterror-on-mongo-replica-set-using-pymongo)
Which makes the dev question if the db is at fault. -- in this case its not*

**Comment by alisaifee** [comment]
> In my and many setups I know where flask-limiter is used, (a wrapper which uses limits library), it is not obvious as to where and how to pass on the connection options for the Database.

To solve this - I think the better solution would be to improve the documentation in flask-limiter (and even here in limits) to make it clearer what the defaults are and how to provide ones own configuration.

**Comment by alisaifee** [comment]
> [ServerSelectionTimeoutError on mongo replica set using pymongo](https://stackoverflow.com/questions/71132796/serverselectiontimeouterror-on-mongo-replica-set-using-pymongo)

The error you shared above seems to be referring to a misconfiguration rather than an actual timeout?

**Comment by Vishwamithra37** [comment]
> > [ServerSelectionTimeoutError on mongo replica set using pymongo](https://stackoverflow.com/questions/71132796/serverselectiontimeouterror-on-mongo-replica-set-using-pymongo)
> 
> The error you shared above seems to be referring to a misconfiguration rather than an actual timeout?

The mongodb forum answers:
https://www.mongodb.com/community/forums/t/what-is-the-recommended-value-for-the-serverselectiontimeoutms-setting-for-atlas/149806


Scale Grid answers:
https://scalegrid.io/blog/mongodb-timeout-settings/#:~:text=By%20default%2C%20this%20timeout%20is,this%20setting%20does%20affect%20performance.

**Comment by Vishwamithra37** [comment]
> > [ServerSelectionTimeoutError on mongo replica set using pymongo](https://stackoverflow.com/questions/71132796/serverselectiontimeouterror-on-mongo-replica-set-using-pymongo)
> 
> The error you shared above seems to be referring to a misconfiguration rather than an actual timeout?

It is also important to understand that timeout should be long enough by default to make the library more stable rather than quickly go into error mode. As mentioned, timeout is the **Maxiumum time its gonna wait for the transaction/CRUD** to be done.  If the connection is stable enough, this shouldnt be an issue. And in case of sudden mishaps, the system should be able to at least for the minimum time required for the connection to resolve itself. 
(Both in case of Mongodb and other SQL dbs). A quick connect and reconnect should not directly impact any application.

**Comment by alisaifee** [comment]
> And 1 second is not the standard. 
Fair enough. I'd like to propose however, instead of setting a higher timeout by default, how about we just remove the `DEFAULT_OPTIONS` entirely and leave it to the defaults of the underlying pymongo / motor clients?

**Comment by Vishwamithra37** [comment]
> > And 1 second is not the standard.
> 
> Fair enough. I'd like to propose however, instead of setting a higher timeout by default, how about we just remove the `DEFAULT_OPTIONS` entirely and leave it to the defaults of the underlying pymongo / motor clients?

Yes!, that sounds like a good way to handle it too :) . I think we should proceed with removing the default options altogether.

**Comment by alisaifee** [comment]
Thanks for the input and suggestions. Could we close this PR in favour of 55cdfb9a3731a46fcb768fd5dad93dc99534909b?

**Comment by Vishwamithra37** [comment]
> Thanks for the input and suggestions. Could we close this PR in favour of 55cdfb9a3731a46fcb768fd5dad93dc99534909b?

Yep please do :)

**Comment by alisaifee** [comment]
Change available in [3.9.0](https://limits.readthedocs.io/en/stable/changelog.html#v3-9-0)

**Pull request closed without merging**
