### PR TITLE
Implement saslmemcached

### PR DESCRIPTION
**Pull request by rxsegrxup**
This pull request implements saslmemcached via the following uri scheme:

```
saslmemcached://username:password@hostname.tld:port
saslmemcached://username:password@hostname.tld:port,hostname2.tld:port
```

Only one username/password combination can be used at a time

### CODE REVIEW

**Comment by rxsegrxup** [comment]
FYI: In order to properly test sasl, [something like this](https://launchpad.net/~travis-ci/+archive/ubuntu/memcached-sasl) needs to be used.

**Comment by rxsegrxup** [comment]
Closing this until I further understand `cas`

**Comment by rxsegrxup** [comment]
`cas` is now enabled lazily for elastic expiry only

**Comment by alisaifee** [comment]
Hi @rxsegrxup. Thanks for the pull request.

A few thoughts:
* I'm not too keen on changing the memcached client library in the base `MemcachedStorage` class as it would change the dependencies for people already using it and probably break their services upon upgrade.
* I can make the base class a bit more flexible so that all the behavior changes required for `SaslMemcachedStorage` can be done simply by subclassing and overriding certain properties.
* You can then define `SaslMemcachedStorage` in your own code base and it'll get picked up by `limits` as a registered storage backend.

Would that work for your usecase?

Lastly, I'm not clear on the need/usecase of the `configure` method - how will it be called by `Flask-Limiter` for instance?

**Comment by rxsegrxup** [comment]
Hello @alisaifee,
That is a good point to keep in mind. I would however encourage folks to use bmemcached simply because it is thread safe and pylibmc is not. When I find the time I'll be sending a similar PR to [werkzeug](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/contrib/cache.py#L302).

The issue I am facing is that limits cannot be easily customized by flask_limiter such that it knows to use, for example, bmemcached instead of pylibmc. If you can some how make that possible it would be greatly appreciated :).

Lastly, as for the configure method, [here is the intended use](https://github.com/YoApp/flask-limiter/commit/d30842fe71f9d033eb7e86301c815fb482ced04f).
When I originally started changing this I needed to enable/disable some of the "behaviors" of pylibmc. This seemed like the best/easiest way to do it.


I do apologize because this PR has become very convoluted so I am closing it for good this time and will include the details of the intended behavior in an issue.

**Pull request closed without merging**
