### PR TITLE
Add async support with memory and redis storage backends

### PR DESCRIPTION
**Pull request by laurentS**
This addresses issue #60, but is still WIP. Support for more
backends is still needed. So far, I've only implemented memory and redis.

A few notes:
- `async` is a reserved word in python, so we can't name the folder `async`, so I went for the closest `_async`. This means the imports look a little strange, but I don't think it's a disaster.
- unittest only supports testing async code from python3.8, so I converted to pytest format so that we can test on 3.6+. I had to update the tests to use pytest asserts instead of the unittest ones. I find them more readable anyway, but it means that the tests look different across the codebase. (though after pushing my code, I noticed you seem to be moving towards pytest in a new branch, so maybe it's a good thing after all!)
- I've copy/pasted all your tests for storage backends, and adjusted them to support async/pytest. The logic is exactly the same
- given that python 3.6 is already EOL, and 3.7 end of main support is this month, I'd be tempted to support only 3.8+ but that might be too restrictive... Happy to hear your thoughts on this.
- I've renamed the schemes for async backends with a leading `a`, `amemory`, `aredis`... to avoid duplicating the registry logic
- I have tried to type annotate all the code. I find that type annotations help with understanding a new code base, on top of the obvious benefits of typechecking with mypy, etc... There are still a few typing errors reported by mypy however.
- all the new code is formatted with black

Again, this is WIP, but I wanted to get your feedback on this early, before I spend too much time going down the wrong way.

### CODE REVIEW

**Comment by laurentS** [comment]
@alisaifee I had almost forgotten about this PR. Are you waiting for me to add something before you look at it, or you've just not had time yet?

**Comment by thearchitector** [comment]
@alisaifee this would be great, esp as asyncio gets more and more common

**Comment by prryplatypus** [comment]
+1 for this

**Comment by alisaifee** [comment]
@laurentS I'm very sorry for the huge delay in getting this merged. If you're still interested, I've removed support for python < 3.7 in  master and hopefully this should make it easier to integrate?

**Comment by laurentS** [comment]
Definitely still interested. I think one of the contributors to slowapi actually took this async code and released it separately, but it would be great to keep everything in one place if possible.

**Comment by laurentS** [comment]
Here it is https://github.com/laurentS/slowapi/pull/56#issuecomment-933862938

**Comment by alisaifee** [comment]
@laurentS I've managed to syncup this branch: https://github.com/alisaifee/limits/tree/async_limits from yours (I had to resolve a bunch of conflicts since I'd done some linting/documentation/type hinting changes in master - but the essence remains the same).

A minor change is to the actual namespace (`limits.asyncio` instead of `limits._async`)

If you could rebase / reset your branch to what I have in my `async` branch, I'd love to get this PR merged.

**Comment by alisaifee** [comment]
Since I'm making some progress (and have some time these next few weeks) I'll close this PR and wrap this up  in #79

**Pull request closed without merging**
