### PR TITLE
Feature/support redis reset

### PR DESCRIPTION
**Pull request by RobertDeRose**

### CODE REVIEW

**Comment by RobertDeRose** [comment]
Well, there should be no reason this is failing, I tested this against 3.3.5 just like travis and it passes with flying colors.

**Comment by RobertDeRose** [comment]
@alisaifee Any interest in this PR?

**Comment by jprivard** [comment]
I just tested RobertDeRose's PR on a project on which we have a need for this future and it is working flawlessly. The organization I work for would definitely like to have this functionality.

**Comment by alisaifee** [comment]
Sorry, @RobertDeRose I've been caught up with work and hadn't had a chance to look at this properly.

The implementation looks good, and thank you for refactoring. Could I ask you to add some details to the  docstring of the `reset` method with a **warning** that the clear operation in redis could be expensive and should be used with care.

**Comment by RobertDeRose** [comment]
yes I can do that. Thank you for the reply.

**Comment by RobertDeRose** [comment]
All done @alisaifee

**Comment by alisaifee** [comment]
Thanks. LGTM!

**Comment by RobertDeRose** [comment]
@alisaifee This is now in master for a while, any chance we can see it make it into a tagged release?

**Pull request merged**
